<a href="https://colab.research.google.com/github/thecodemaster152/Brief-guide-to-pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


##Introduction to tensor

###Creating Tensor

Pytorch tensor are created using torch.Tensor()

In [3]:
#this is a constant tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()        # get tensor data back as python list

7

In [7]:
scalar_1 = torch.tensor([7,7])
scalar_1

tensor([7, 7])

In [12]:
scalar_1.ndim

1

In [11]:
scalar_2 = torch.tensor([[7,7],[6,6]])
scalar_2 , scalar_2.ndim

(tensor([[7, 7],
         [6, 6]]),
 2)

In [15]:
scalar_2.size()

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor([[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]])

TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR.shape

torch.Size([3, 3])

In [18]:
TENSOR_1 = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR_1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR_1.shape

torch.Size([1, 3, 3])

##Random Tensor

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [20]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2522, 0.2060, 0.9199, 0.8064],
        [0.3147, 0.0732, 0.9811, 0.6583],
        [0.6846, 0.9512, 0.6681, 0.0745]])

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [22]:
random_image_size_tensor

tensor([[[0.8355, 0.2282, 0.8831,  ..., 0.9305, 0.8634, 0.0305],
         [0.3063, 0.6329, 0.0255,  ..., 0.0018, 0.6640, 0.5636],
         [0.1087, 0.5939, 0.4456,  ..., 0.4267, 0.4730, 0.2950],
         ...,
         [0.1304, 0.3705, 0.4184,  ..., 0.4509, 0.8112, 0.5767],
         [0.3384, 0.1835, 0.6497,  ..., 0.1057, 0.8270, 0.4764],
         [0.7139, 0.2320, 0.8385,  ..., 0.3954, 0.2320, 0.8390]],

        [[0.4878, 0.8253, 0.0417,  ..., 0.9201, 0.6735, 0.9555],
         [0.2305, 0.9734, 0.0838,  ..., 0.5380, 0.0821, 0.4611],
         [0.0675, 0.1575, 0.7161,  ..., 0.4370, 0.7185, 0.0771],
         ...,
         [0.0479, 0.6638, 0.9939,  ..., 0.1882, 0.0596, 0.8242],
         [0.1382, 0.7870, 0.9699,  ..., 0.6952, 0.4788, 0.2438],
         [0.3839, 0.1331, 0.8798,  ..., 0.8288, 0.4808, 0.3928]],

        [[0.5757, 0.5514, 0.3263,  ..., 0.8257, 0.3112, 0.3466],
         [0.7215, 0.4771, 0.1213,  ..., 0.9305, 0.3235, 0.5989],
         [0.8191, 0.3514, 0.2841,  ..., 0.1590, 0.2733, 0.

###Zeros and ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(2, 3, 4))
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [26]:
# Create a tensor of all ones
ones = torch.ones(size=(4, 3, 4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

###Creating a range of tensors and tensors-like

In [28]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##Reshaping, stacking, squeezing and unsqueezing tensors
Reshaping - reshapes an input tensor to a defined shape

View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

Squeeze - removes all 1 dimensions from a tensor

Unsqueeze - add a 1 dimension to a target tensor

Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [31]:
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [32]:
x_reshaped = x.reshape(1,2,4)
x_reshaped, x_reshaped.shape

(tensor([[[1., 2., 3., 4.],
          [5., 6., 7., 8.]]]),
 torch.Size([1, 2, 4]))

In [35]:
x_1 = torch.arange(1. ,10.)
x_1 , x_1.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [37]:
x_1_reshaped = x_1.reshape(1,2,4)                  #this  gives size error
x_1_reshaped, x_1_reshaped.shape

RuntimeError: shape '[1, 2, 4]' is invalid for input of size 9

In [44]:
# Change the view
y = torch.arange(1. , 10.)
z = y.view(1, 9)
y, y.shape, z, z.shape                   #look how the size is changing

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

    Quick mental model
    (9,)     → one flat vector
    (1, 9)   → one sample with 9 features
    (9, 1)   → 9 samples with 1 feature

In [53]:
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])

In [54]:
x_stacked.shape

torch.Size([8, 4])